### ISSUE TITLE
Chromedriver outdated

### ISSUE THREAD

**Issue by DavidWarmerdam** [mirabeau-nl/WbTstr.Net#25]
Hi, could you please update the bundled Chromedriver? The bundled driver is not compatible with Chrome 62 onwards. Thanks

**Comment by onnovalkering** [comment]
Hi @DavidWarmerdam,

Some way I don't have write rights for this WbTstr.Net repository anymore. Perhaps @lazytesting does.
Steps are: _chromedriver.exe_ (located in _/FluentAutomation.SeleniumWebDriver/3rdPartyLib_) has to be replaced with an up-to-date version, ~~then do a build with Visual Studio of the solution and a new package for NuGet will be generated (project folder root), which can then be uploaded to NuGet~~, and head to Bamboo for the CI/CD jobs to upload the new package to NuGet.

If nobody can update the .exe in the assembly, there is another workaround. The routine that extracts the .exe from the assembly checks the local path (where the project DLL's are located, probably _/bin/Debug_) or any path in the PATH environment variable for an override. If _Customchromedriver.exe_ is present in one of the paths described above it will use that one, instead of the bundled chromedriver. See [EmbeddedResources.cs](https://github.com/mirabeau-nl/WbTstr.Net/blob/master/FluentAutomation/EmbeddedResources.cs) for the details.

Also note that in the rewritten version of WbTstr, we use a seperatly updatable NuGet package to overcome this issue, see the the [WbTstr](https://github.com/wbtstr) repositories.

**Comment by DavidWarmerdam** [comment]
Thanks @onnovalkering for explaining how to replace the driver. You mention the rewritten version of WbTstr; would you consider this rewritten version fit for implementation already? The API seems pretty much alike, so I might replace WbTstr with the rewritten one.

**Comment by onnovalkering** [comment]
@DavidWarmerdam, well development is ~95% done, and I'm confident it is usable. However it hasn't undergo any actual integration testing, because it lacks a proper testbed. So I would not rely, for this moment, on it for production-important testing.

I'm interesting though in your feedback on the new version, especially the newly added features, if you decide to take it for a test ride :).

**Comment by DavidWarmerdam** [comment]
@onnovalkering  I will leave this issue open until a new nuget package can be uploaded. Will let you know once I've tried the new WbTstr ;)

**Comment by DavidWarmerdam** [comment]
@onnovalkering I've tried out your suggested solutions, but in both cases I get an empty Chrome window with "data;" in the address bar and a Chromedriverprocess with the following message: "DevTools listening on ws://127.0.0.1:12278/devtools/browser/11154a6a-7a37-4b9b-9b31-9dce67803155"

What I did was: 
-Replacing Chromedriver.exe with version 2.33 in 3rdPartyLib folder, do a rebuild and taking FluentAutomation.SeleniumWebDriver.dll and WebDriver.dll and putting them in the bin/debug folders of my solution.
-Putting a new version of Chromedriver (v2.33) with name Customchromedriver.exe in the bin/debug folder.

To double check I've taken the last known working Chromedriver (v2.29) and put this in the bin/debug folder. I've changed the name of the exe to Customchromedriver.exe. The same situation occurs. 

Do you know what else I can try?

**Comment by onnovalkering** [comment]
@DavidWarmerdam, hmm oke, I really think the only option is to get to someone with write access to the repository (anyone within the [Mirabeau organisation](https://github.com/mirabeau-nl) on GitHub has access, I suppose), or request access yourself. 

Now I think of it, the actual uploading to NuGet is done via some automated CI/CD jobs, to be able to upload it under the Mirabeau account to NuGet, if you search for WbTstr.Net on Bamboo you should find it.

**Comment by onnovalkering** [comment]
@DavidWarmerdam, I've updated the _chromedriver.exe_ in the repository to 2.33.0

I can't access Bamboo remotely, so someone else must start the Build / Release jobs (providing version 1.4.3) on Bamboo to actually upload a new package to NuGet. I'm sure Maarten or Catelijne can do this.

**Comment by DavidWarmerdam** [comment]
@onnovalkering Thanks! The 1.4.3 package is now available on Nuget.
